name: vdd-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - coverage=4.5.*
  - ddt=1.2.*
  - gspread=3.1.*
  - mock=3.0.*
  - numpy=1.16.*
  - oauth2client=4.1.*
  - pandas=0.24.*
  - pypandoc=1.*
  - xdg=1.0.*
  - xlrd=1.2.*
